[package]
name = "types"
version = "0.1.0"
edition = "2021"
authors = ["Yang Zhang <z2634541542@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"